/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class byr_ipv4over6_MainActivity */

#ifndef _Included_byr_ipv4over6_MainActivity
#define _Included_byr_ipv4over6_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     byr_ipv4over6_MainActivity
 * Method:    StringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_byr_ipv4over6_MainActivity_StringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     byr_ipv4over6_MainActivity
 * Method:    connect4o6Byr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_byr_ipv4over6_MainActivity_connect4o6Byr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
