/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class byr_ipv4over6_MainActivity_GuiInfo */

#ifndef _Included_byr_ipv4over6_MainActivity_GuiInfo
#define _Included_byr_ipv4over6_MainActivity_GuiInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
